### ISSUE TITLE
Release 0.5

### ISSUE THREAD

**Issue by bernhardmgruber** [alpaka-group/llama#694]
This issue tracks all missing steps for the LLAMA 0.5 release

- [x] All examples must build.
- [x] All unit tests must build and pass.
- [x] The documentation must build (check readthedocs).
- [x] Verify that the documentation is up-to-date.
- [x] Verify that the README.md is up-to-date.
- [x] Verify that the CHANGELOG.md is up-to-date.
- [x] Replace `.zenodo.json` by `CITATION.cff`: #696 
- [x] Verify that .zenodo.json is up-to-date, especially regarding contributors.
- [x] Bump the version number in llama.hpp and docs/conf.py: #695 
- [x] Test in downstream projects (AdePT).
- [x] Test in downstream projects (picongpu). Works with nvcc 11.8, but not with 12.0. It is not clear whether the error for the latter stems from LLAMA or the glue code for the integration :/
- [x] Merge outstanding PR: #693
- [x] Merge outstanding PR: #698
- [x] Set release date in CHANGELOG.md and commit
- [x] Draft a new release on GitHub: https://github.com/alpaka-group/llama/releases.
- [x] Release

**Comment by bernhardmgruber** [comment]
Released: https://github.com/alpaka-group/llama/releases/tag/v0.5
